# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indiatoday',
            fields=[
                ('Headline', models.TextField()),
                ('Link', models.TextField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ndtv',
            fields=[
                ('Headline', models.TextField()),
                ('Link', models.TextField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Republic',
            fields=[
                ('Headline', models.TextField()),
                ('Link', models.TextField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
