# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indiatoday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headline', models.TextField()),
                ('Link', models.TextField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Category', models.TextField(null=True)),
                ('Sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Ndtv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headline', models.TextField()),
                ('Link', models.TextField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Category', models.TextField(null=True)),
                ('Sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Republic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headline', models.TextField()),
                ('Link', models.TextField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Category', models.TextField(null=True)),
                ('Sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
