# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiatoday',
            name='Category',
            field=models.TextField(default='uncategorized'),
        ),
        migrations.AddField(
            model_name='indiatoday',
            name='Sentiment',
            field=models.TextField(default='Positive'),
        ),
        migrations.AddField(
            model_name='ndtv',
            name='Category',
            field=models.TextField(default='uncategorized'),
        ),
        migrations.AddField(
            model_name='ndtv',
            name='Sentiment',
            field=models.TextField(default='Positive'),
        ),
        migrations.AddField(
            model_name='republic',
            name='Category',
            field=models.TextField(default='uncategorized'),
        ),
        migrations.AddField(
            model_name='republic',
            name='Sentiment',
            field=models.TextField(default='Positive'),
        ),
    ]
