# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_hindstan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hindstan',
            new_name='Hindustan',
        ),
    ]
