# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20181116_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiatoday',
            name='Category',
            field=models.TextField(default='uncategorized', null=True),
        ),
        migrations.AlterField(
            model_name='indiatoday',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='indiatoday',
            name='Sentiment',
            field=models.TextField(default='Positive', null=True),
        ),
        migrations.AlterField(
            model_name='ndtv',
            name='Category',
            field=models.TextField(default='uncategorized', null=True),
        ),
        migrations.AlterField(
            model_name='ndtv',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ndtv',
            name='Sentiment',
            field=models.TextField(default='Positive', null=True),
        ),
        migrations.AlterField(
            model_name='republic',
            name='Category',
            field=models.TextField(default='uncategorized', null=True),
        ),
        migrations.AlterField(
            model_name='republic',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='republic',
            name='Sentiment',
            field=models.TextField(default='Positive', null=True),
        ),
    ]
