# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20181118_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='republic',
            old_name='Headline',
            new_name='headline',
        ),
    ]
