# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20181118_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='republic',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='hindustan',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ndtv',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
