# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20181117_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiatoday',
            name='Category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='indiatoday',
            name='Sentiment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ndtv',
            name='Category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ndtv',
            name='Sentiment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='republic',
            name='Category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='republic',
            name='Sentiment',
            field=models.TextField(null=True),
        ),
    ]
