# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20181117_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndtv',
            name='Link',
            field=models.TextField(unique=True),
        ),
    ]
