# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20181117_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiatoday',
            name='Link',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='republic',
            name='Link',
            field=models.TextField(unique=True),
        ),
    ]
