# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20181216_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thehindu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Zeenews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
