# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_thehindu_zeenews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thehindu',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='zeenews',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
