# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-11 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_indextop10'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextop10',
            name='frequency',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
